package model;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import model.common.AppModule;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 26 12:42:48 GMT+02:00 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


    public Integer getBranchName(Integer empId, String d1, String d2, Integer yeart, Integer flage) {
        CallableStatement cs = null;
        try {
            cs = getDBTransaction().createCallableStatement("begin ? := findEmpData1(?,?,?,?,?); end;", 0);
            cs.registerOutParameter(1, Types.INTEGER);
            cs.setInt(2, empId);
            cs.setString(3, d1);
            cs.setString(4, d2);
            cs.setInt(5, yeart);
            cs.setInt(6, flage);
            cs.executeUpdate();
            return cs.getInt(1);
        } catch (SQLException e) {
            throw new JboException(e);
        }
    }


    /**
     * Container's getter for VO1_1.
     * @return VO1_1
     */
    public ViewObjectImpl getVO1_1() {
        return (ViewObjectImpl) findViewObject("VO1_1");
    }

    /**
     * Container's getter for VO2_1.
     * @return VO2_1
     */
    public ViewObjectImpl getVO2_1() {
        return (ViewObjectImpl) findViewObject("VO2_1");
    }


    /**
     * Container's getter for VO3_1.
     * @return VO3_1
     */
    public ViewObjectImpl getVO3_1() {
        return (ViewObjectImpl) findViewObject("VO3_1");
    }


    /**
     * Container's getter for VO5_1.
     * @return VO5_1
     */
    public ViewObjectImpl getVO5_1() {
        return (ViewObjectImpl) findViewObject("VO5_1");
    }

    /**
     * Container's getter for VO4_1.
     * @return VO4_1
     */
    public ViewObjectImpl getVO4_1() {
        return (ViewObjectImpl) findViewObject("VO4_1");
    }

    /**
     * Container's getter for VO6_1.
     * @return VO6_1
     */
    public ViewObjectImpl getVO6_1() {
        return (ViewObjectImpl) findViewObject("VO6_1");
    }
}

