package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 02 14:27:03 GMT+02:00 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    Integer getBranchName(Integer empId, String d1, String d2, Integer yeart, Integer flage);
}

